# Generated by Django 6.0.8 on 2026-08-31 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Submitted')),
                ('primary', models.CharField(blank=True, choices=[('management', 'Management'), ('creative', 'Creative'), ('technical', 'Technical'), ('audience', 'Audience'), ('ethics', 'Ethics')], max_length=20, verbose_name='Primary pathway')),
                ('ascending', models.CharField(blank=True, choices=[('management', 'Management'), ('creative', 'Creative'), ('technical', 'Technical'), ('audience', 'Audience'), ('ethics', 'Ethics')], max_length=20, verbose_name='Ascending pathway')),
                ('is_pure', models.BooleanField(default=False, verbose_name='Pure result')),
                ('all_skip', models.BooleanField(default=False, help_text='Participant answered “not interested” to every statement.', verbose_name='Flagged for outreach')),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Statement')),
                ('pathway', models.CharField(choices=[('management', 'Management'), ('creative', 'Creative'), ('technical', 'Technical'), ('audience', 'Audience'), ('ethics', 'Ethics')], max_length=20, verbose_name='Pathway')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive statements are not shown to new participants.', verbose_name='Active')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='quiz_statem_is_acti_030bc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('confident', 'I can do this with some confidence'), ('growing', 'I am actively trying to get better at this'), ('skip', 'I am not interested in this')], max_length=20, verbose_name='Rating')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.response', verbose_name='Response')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='quiz.statement', verbose_name='Statement')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('response', 'statement'), name='unique_answer_per_statement')],
            },
        ),
    ]
