# Generated by Django 6.0.8 on 2026-09-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_space_statement_slashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='depth',
            field=models.CharField(blank=True, default='', help_text="Pathways where the respondent gave both a confident and an actively-trying answer. Independent of primary/ascending; stored wrapped in commas so a specific pathway can be filtered for without matching another pathway's slug as a substring.", max_length=80, verbose_name='Depth pathway(s)'),
        ),
    ]
